"""
Script to add comprehensive attraction data for Tunisia, Morocco, and Algeria
This data should be added to the demo_attractions dictionary in the attraction_detail function in views.py

Usage: Copy the ATTRACTIONS_DATA sections and paste them into the appropriate country sections
in the demo_attractions dictionary in core/views.py starting around line 11500
"""

# TUNISIA ATTRACTIONS - Add these to demo_attractions['tunisia']
TUNISIA_ATTRACTIONS = {
    "dougga-ancient-city": {
        "id": "dougga-ancient-city",
        "name": "Dougga Ancient City",
        "location": "Dougga, Tunisia",
        "description": "The most impressive and best-preserved Roman site in Tunisia, a UNESCO World Heritage Site.",
        "long_description": "Dougga is Tunisia's most impressive Roman site and one of the best-preserved Roman towns in the Mediterranean. Founded as a Numidian settlement, the city flourished under Roman rule and features magnificent temples, theaters, and public buildings spread across a hilltop. The site provides stunning panoramic views and showcases the wealth and architectural sophistication of Roman North Africa.",
        "historical_significance": "Founded as a Numidian town, Dougga became a Roman municipality under Septimius Severus. The city reached its peak in the 2nd-3rd centuries AD.",
        "cultural_impact": "UNESCO World Heritage Site since 1997, Dougga is considered one of the finest examples of a Roman small town in North Africa.",
        "best_time_to_visit": "March to May or October to November (mild weather, fewer crowds)",
        "how_to_get_there": "Located 110km southwest of Tunis; accessible by taxi, bus, or organized tours",
        "entrance_fees": "12 TND (about $4 USD) for adults",
        "opening_hours": "8:30 AM - 5:30 PM daily (7:00 PM in summer)",
        "what_to_wear": "Comfortable hiking shoes; hat and sunscreen; light, breathable clothing",
        "guided_tours": "Highly recommended; local guides available at the entrance",
        "nearby_attractions": [
            "Capitol Temple",
            "Theater of Dougga",
            "House of Trifolium",
            "Baths of the Cyclops",
        ],
        "facts": [
            "UNESCO World Heritage Site since 1997",
            "The Roman theater seats 3,500 spectators",
            "Contains the best-preserved Capitol temple in North Africa",
            "The site covers 70 hectares on a hillside",
            "Features unique Libyan-Punic mausoleum",
        ],
        "visitor_tips": [
            "Wear sturdy shoes as the site is spread across a hillside",
            "Allow 3-4 hours to explore the entire site",
            "Bring water and snacks as facilities are limited",
            "The Capitol offers spectacular views",
            "Visit early morning for best light and fewer visitors",
        ],
        "photos": [
            "https://images.unsplash.com/photo-1533105079780-92b9be482077?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
            "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        ],
        "coordinates": "36.4228° N, 9.2194° E",
        "annual_visitors": "150,000",
        "climate": "Mediterranean climate with hot, dry summers",
        "unesco_status": "UNESCO World Heritage Site since 1997",
    },
    "bardo-museum": {
        "id": "bardo-museum",
        "name": "Bardo National Museum",
        "location": "Tunis, Tunisia",
        "description": "The world's greatest collection of Roman mosaics housed in a former Ottoman palace.",
        "long_description": "The Bardo National Museum houses the world's finest collection of Roman mosaics, along with artifacts from Tunisia's Punic, Roman, Christian, and Islamic periods. Set in a magnificent 19th-century Ottoman palace, the museum showcases Tunisia's rich history through stunning mosaics depicting mythological scenes, daily life, and natural scenes from ancient times.",
        "historical_significance": "Established in 1888, the museum occupies a former beylical palace and has become Africa's premier archaeological museum.",
        "cultural_impact": "The Bardo houses the world's most important collection of Roman mosaics and is a treasure trove of Mediterranean history.",
        "best_time_to_visit": "Year-round; weekdays are less crowded",
        "how_to_get_there": "Located 4km west of Tunis center; accessible by metro, taxi, or bus",
        "entrance_fees": "11 TND (about $3.50 USD) for adults",
        "opening_hours": "9:00 AM - 5:00 PM (closed Mondays)",
        "what_to_wear": "Casual clothing; comfortable shoes for walking",
        "guided_tours": "Highly recommended; audio guides available in multiple languages",
        "nearby_attractions": [
            "Tunis Medina",
            "Zitouna Mosque",
            "Carthage ruins",
            "Sidi Bou Said",
        ],
        "facts": [
            "Contains the world's largest collection of Roman mosaics",
            "Housed in a 19th-century Ottoman palace",
            "Covers 8,000 years of Tunisian history",
            "Features over 100 rooms of exhibitions",
            "The Virgil mosaic is one of the most famous pieces",
        ],
        "visitor_tips": [
            "Allow 2-3 hours for a thorough visit",
            "Photography allowed without flash",
            "Visit on weekdays to avoid crowds",
            "The Virgil and Ulysses mosaics are must-sees",
            "Combine with Carthage for a historical day trip",
        ],
        "photos": [
            "https://images.unsplash.com/photo-1539650116574-75c0c6d0b7ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"
        ],
        "coordinates": "36.8086° N, 10.1347° E",
        "annual_visitors": "500,000",
        "climate": "Mediterranean climate",
        "architecture": "Ottoman palace architecture",
    },
    "djerba-island": {
        "id": "djerba-island",
        "name": "Djerba Island",
        "location": "Djerba, Tunisia",
        "description": "A Mediterranean island paradise with ancient synagogues, pristine beaches, and traditional crafts.",
        "long_description": "Djerba is Tunisia's largest island and a popular resort destination known for its beautiful beaches, ancient history, and cultural diversity. The island is home to one of the world's oldest Jewish communities and features the ancient El Ghriba Synagogue. Djerba offers a unique blend of Berber, Arab, and Jewish cultures, with traditional crafts, stunning beaches, and historic sites.",
        "historical_significance": "Djerba has been continuously inhabited for over 2,500 years and is home to one of the oldest Jewish communities in the world.",
        "cultural_impact": "The island represents Tunisia's cultural diversity and religious tolerance, with centuries of coexistence between different faiths.",
        "best_time_to_visit": "April to June or September to November (perfect beach weather)",
        "how_to_get_there": "Djerba-Zarzis International Airport; also accessible by ferry from the mainland",
        "entrance_fees": "Varies by attraction; synagogue visit is 5 TND",
        "opening_hours": "Beaches 24/7; synagogue 8:00 AM - 6:00 PM",
        "what_to_wear": "Beach attire for coastal areas; modest clothing for religious sites",
        "guided_tours": "Island tours available; cultural tours recommended for historical sites",
        "nearby_attractions": [
            "El Ghriba Synagogue",
            "Houmt Souk",
            "Guellala Museum",
            "Djerba Explore Park",
        ],
        "facts": [
            "Tunisia's largest island at 514 square kilometers",
            "Home to North Africa's oldest synagogue (586 BC)",
            "Known for traditional pottery and weaving",
            "Features over 300 mosques",
            "Connected to mainland by ancient Roman causeway",
        ],
        "visitor_tips": [
            "Rent a bike or scooter to explore the island",
            "Visit El Ghriba Synagogue during the annual pilgrimage",
            "Try traditional Djerban bread and olive oil",
            "Explore the pottery workshops in Guellala",
            "Combine beach time with cultural exploration",
        ],
        "photos": [
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
            "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
        ],
        "coordinates": "33.8076° N, 10.8451° E",
        "annual_visitors": "1,200,000",
        "climate": "Mediterranean climate with mild winters",
        "cultural_heritage": "Multi-faith community with Islamic, Jewish, and Christian sites",
    },
    "matmata": {
        "id": "matmata",
        "name": "Matmata Troglodyte Houses",
        "location": "Matmata, Tunisia",
        "description": "Underground Berber dwellings carved into the rock, famous as Star Wars filming locations.",
        "long_description": "Matmata is a small Berber village famous for its unique underground troglodyte dwellings. These crater-like pit houses are carved into soft sandstone, providing natural insulation from the extreme desert climate. The area gained international fame as a filming location for Star Wars, where Luke Skywalker's home was set. Today, visitors can explore these ancient dwellings and even stay in converted hotels.",
        "historical_significance": "The troglodyte tradition dates back centuries as Berbers created these homes for protection and climate control in the harsh desert environment.",
        "cultural_impact": "Matmata represents traditional Berber architecture and gained global fame through Star Wars, bringing tourism to this remote region.",
        "best_time_to_visit": "October to April (cooler temperatures)",
        "how_to_get_there": "Located 45km south of Gabès; accessible by taxi, bus, or organized tours",
        "entrance_fees": "Free to explore village; some hotels charge viewing fees (5-10 TND)",
        "opening_hours": "24/7 access; individual sites have varying hours",
        "what_to_wear": "Comfortable walking shoes; light, breathable clothing; sun protection",
        "guided_tours": "Local guides available; Star Wars tours popular",
        "nearby_attractions": [
            "Hotel Sidi Driss (Star Wars location)",
            "Tamezret village",
            "Berber Museum",
            "Toujane",
        ],
        "facts": [
            "Troglodyte houses stay naturally cool in summer and warm in winter",
            "Hotel Sidi Driss was Luke Skywalker's home in Star Wars",
            "Berbers have lived in underground homes here for centuries",
            "Houses are dug up to 10 meters deep",
            'The village was "discovered" by Western researchers in 1967',
        ],
        "visitor_tips": [
            "Stay overnight in a troglodyte hotel for the full experience",
            "Visit the Star Wars film location at Hotel Sidi Driss",
            "Respect that many homes are still inhabited",
            "Try traditional Berber food",
            "Combine with a visit to nearby Ksar Hadada",
        ],
        "photos": [
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"
        ],
        "coordinates": "33.5447° N, 9.9717° E",
        "annual_visitors": "200,000",
        "climate": "Desert climate with extreme temperature variations",
        "film_location": "Star Wars Episode IV filming location",
    },
    "tozeur-oasis": {
        "id": "tozeur-oasis",
        "name": "Tozeur Oasis",
        "location": "Tozeur, Tunisia",
        "description": "A stunning desert oasis with date palms, traditional architecture, and gateway to the Sahara.",
        "long_description": "Tozeur is a desert oasis town and the gateway to the Tunisian Sahara. The town features beautiful Islamic architecture with distinctive geometric brick patterns, lush palm groves with over 400,000 date palms, and proximity to spectacular desert landscapes. Tozeur serves as a base for exploring the salt lakes (chotts), mountain oases, and Star Wars filming locations in the region.",
        "historical_significance": "Tozeur has been an important oasis town on trans-Saharan trade routes for centuries, serving as a commercial and religious center.",
        "cultural_impact": "The town represents desert oasis culture and traditional Islamic architecture unique to southern Tunisia.",
        "best_time_to_visit": "November to March (cooler desert temperatures)",
        "how_to_get_there": "Tozeur-Nefta International Airport; also accessible by bus from Tunis (8 hours)",
        "entrance_fees": "Free for medina; excursions vary (30-100 TND)",
        "opening_hours": "24/7 access to town; excursions during daylight",
        "what_to_wear": "Light, breathable desert clothing; sun protection; comfortable shoes",
        "guided_tours": "4x4 desert tours highly recommended; camel treks available",
        "nearby_attractions": [
            "Chebika Oasis",
            "Chott el Djerid",
            "Tamerza Canyon",
            "Mides Canyon",
        ],
        "facts": [
            "Contains over 400,000 date palms in its palmerie",
            "Features unique geometric brickwork architecture",
            "Gateway to the Tunisian Sahara Desert",
            "Nearby Chott el Djerid is one of Africa's largest salt lakes",
            "Several Star Wars locations nearby",
        ],
        "visitor_tips": [
            "Book 4x4 excursions to mountain oases",
            "Visit the palmerie on foot or by horse-drawn carriage",
            "Try deglet nour dates, considered the world's finest",
            "Explore the old medina with its distinctive architecture",
            "Sunrise and sunset at Chott el Djerid are spectacular",
        ],
        "photos": [
            "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"
        ],
        "coordinates": "33.9197° N, 8.1339° E",
        "annual_visitors": "250,000",
        "climate": "Desert climate; extremely hot in summer",
        "special_features": "Star Wars filming locations nearby",
    },
    "sousse-medina": {
        "id": "sousse-medina",
        "name": "Sousse Medina and Ribat",
        "location": "Sousse, Tunisia",
        "description": "A UNESCO-listed coastal medina with a historic ribat fortress and beautiful Arab-Islamic architecture.",
        "long_description": "The Medina of Sousse is one of Tunisia's finest examples of Arab-Islamic architecture and a UNESCO World Heritage Site. The compact medina is dominated by its impressive ribat, a fortress-monastery dating from the 8th century. The medina features traditional souks, the Great Mosque, and well-preserved city walls, offering visitors an authentic glimpse into Tunisia's medieval Islamic past.",
        "historical_significance": "Founded in 859 AD, the ribat served as both a military fortress and religious retreat, protecting the coast from Byzantine naval attacks.",
        "cultural_impact": "The ribat is one of the oldest and best-preserved Islamic fortifications in North Africa.",
        "best_time_to_visit": "April to June or September to November (mild weather)",
        "how_to_get_there": "Located in Sousse city center; accessible by train, bus, or taxi from Tunis (2 hours)",
        "entrance_fees": "10 TND for ribat and archaeological museum",
        "opening_hours": "8:00 AM - 7:00 PM (summer); 9:00 AM - 5:00 PM (winter)",
        "what_to_wear": "Modest clothing; comfortable shoes for walking",
        "guided_tours": "Available; audio guides at ribat entrance",
        "nearby_attractions": [
            "Great Mosque of Sousse",
            "Archaeological Museum",
            "Sousse Beach",
            "Port El Kantaoui",
        ],
        "facts": [
            "UNESCO World Heritage Site since 1988",
            "The ribat dates from 787 AD",
            "Contains 73 rooms across three floors",
            "The watchtower offers panoramic views",
            "One of the best-preserved ribats in the Maghreb",
        ],
        "visitor_tips": [
            "Climb the watchtower for spectacular views",
            "Visit the archaeological museum in the medina",
            "Explore the traditional souks for local crafts",
            "Respect prayer times at the Great Mosque",
            "Combine with beach time at nearby resorts",
        ],
        "photos": [
            "https://images.unsplash.com/photo-1539650116574-75c0c6d0b7ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80"
        ],
        "coordinates": "35.8256° N, 10.6411° E",
        "annual_visitors": "400,000",
        "unesco_status": "UNESCO World Heritage Site since 1988",
        "climate": "Mediterranean climate",
    },
}

print("Tunisia attractions data ready!")
print(f"Added {len(TUNISIA_ATTRACTIONS)} detailed attractions for Tunisia")
print("\\nAttractions included:")
for key, value in TUNISIA_ATTRACTIONS.items():
    print(f"  - {value['name']}")
