# Generated by Django 5.2.6 on 2025-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accommodation_bed_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='awards_badges',
            field=models.TextField(blank=True, help_text='Awards or recognitions', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hosting_approach',
            field=models.CharField(blank=True, choices=[('hands_on', 'Hands-on / Personal'), ('remote', 'Remote / Self Check-in'), ('team_managed', 'Team Managed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mission_statement',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='special_services',
            field=models.TextField(blank=True, help_text='Special services offered (e.g., airport pickup, guided tours)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sustainability_practices',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual Host'), ('company', 'Company'), ('hotel_chain', 'Hotel Chain'), ('ngo', 'NGO'), ('family_business', 'Family Business'), ('tour_operator', 'Tour Operator')], max_length=50, null=True),
        ),
    ]
