# Generated by Django 5.2.6 on 2025-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rentalcar_rentalcarphoto_tourguide_tourguidephoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcar',
            name='bike_rack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='child_seat_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='cross_border_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='late_return_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='roof_rack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='ski_rack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='vin_number',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='accessibility',
            field=models.TextField(blank=True, help_text='Accessibility options (e.g., Wheelchair accessible, Family-friendly)'),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='covid_safety',
            field=models.TextField(blank=True, help_text='COVID-19 safety measures'),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='equipment_provided',
            field=models.TextField(blank=True, help_text='Equipment you provide (e.g., Audio guides, Maps, Water)'),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='reviews_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='total_tours_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='tour_types_offered',
            field=models.TextField(blank=True, help_text='Types of tours you offer (e.g., Walking tours, Bus tours, Private tours)'),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
