# Generated by Django 5.2.6 on 2025-10-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reward_geniusprofile_booking_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banking_document',
            field=models.FileField(blank=True, help_text='Bank account verification document', null=True, upload_to='verification_documents/banking/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banking_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_license',
            field=models.FileField(blank=True, help_text='Business registration or license document', null=True, upload_to='verification_documents/business/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_license_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_document',
            field=models.FileField(blank=True, help_text="Government-issued ID (passport, driver's license, etc.)", null=True, upload_to='verification_documents/identity/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_document',
            field=models.FileField(blank=True, help_text='Liability insurance certificate', null=True, upload_to='verification_documents/insurance/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_document',
            field=models.FileField(blank=True, help_text='Tax registration or EIN document', null=True, upload_to='verification_documents/tax/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
