# Generated by Django 5.2.6 on 2025-10-10 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_banking_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Set to True if listing needs admin approval after edits'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rental_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Set to True if listing needs admin approval after edits'),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Set to True if listing needs admin approval after edits'),
        ),
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
    ]
